repos:
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    - id: black
      entry: black --check

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8

  - repo: local
    hooks:
    - id: pyright
      name: pyright
      files: '^core/.*\.py'
      entry: bash -c 'cd core && poetry run pyright "$@"'
      language: system
      pass_filenames: false
      types: [python]
    - id: pyright
      name: pyright
      files: '^cli/.*\.py'
      entry: bash -c 'cd cli && poetry run pyright "$@"'
      language: system
      pass_filenames: false
      types: [python]
    - id: pyright
      name: pyright
      files: '^engine/.*\.py'
      entry: bash -c 'cd engine && poetry run pyright "$@"'
      language: system
      pass_filenames: false
      types: [python]
    - id: pyright
      name: pyright
      files: '^server/.*\.py'
      entry: bash -c 'cd server && poetry run pyright "$@"'
      language: system
      pass_filenames: false
      types: [python]
    - id: pyright
      name: pyright
      files: '^meta/.*\.py'
      entry: bash -c 'cd meta && poetry run pyright "$@"'
      language: system
      pass_filenames: false
      types: [python]
    - id: pyright
      name: pyright
      files: '^api/.*\.py'
      entry: bash -c 'cd api && poetry run pyright "$@"'
      language: system
      pass_filenames: false
      types: [python]