repos:
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    - id: black
      entry: black --check

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
