FROM ubuntu:20.04

LABEL oremda.name=add \
  oremda.ports.input.scalars.type=data \
  oremda.ports.input.meta.type=meta \
  oremda.ports.output.scalars.type=data \
  oremda.ports.output.meta.type=meta \
  oremda.params.foo.type=number \
  oremda.params.foo.required=True \
  oremda.params.foo.default=0
